%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'QPMwCredit_24_5_22_nim';
M_.dynare_version = '5.1';
oo_.dynare_version = '5.1';
options_.dynare_version = '5.1';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(17,1);
M_.exo_names_tex = cell(17,1);
M_.exo_names_long = cell(17,1);
M_.exo_names(1) = {'eps_ygap_row'};
M_.exo_names_tex(1) = {'eps\_ygap\_row'};
M_.exo_names_long(1) = {'eps_ygap_row'};
M_.exo_names(2) = {'eps_pie_row'};
M_.exo_names_tex(2) = {'eps\_pie\_row'};
M_.exo_names_long(2) = {'eps_pie_row'};
M_.exo_names(3) = {'eps_RS_row'};
M_.exo_names_tex(3) = {'eps\_RS\_row'};
M_.exo_names_long(3) = {'eps_RS_row'};
M_.exo_names(4) = {'eps_piest_row'};
M_.exo_names_tex(4) = {'eps\_piest\_row'};
M_.exo_names_long(4) = {'eps_piest_row'};
M_.exo_names(5) = {'eps_RRst_row'};
M_.exo_names_tex(5) = {'eps\_RRst\_row'};
M_.exo_names_long(5) = {'eps_RRst_row'};
M_.exo_names(6) = {'eps_gst_row'};
M_.exo_names_tex(6) = {'eps\_gst\_row'};
M_.exo_names_long(6) = {'eps_gst_row'};
M_.exo_names(7) = {'eps_cb'};
M_.exo_names_tex(7) = {'eps\_cb'};
M_.exo_names_long(7) = {'eps_cb'};
M_.exo_names(8) = {'eps_ygap'};
M_.exo_names_tex(8) = {'eps\_ygap'};
M_.exo_names_long(8) = {'eps_ygap'};
M_.exo_names(9) = {'eps_pie'};
M_.exo_names_tex(9) = {'eps\_pie'};
M_.exo_names_long(9) = {'eps_pie'};
M_.exo_names(10) = {'eps_RS'};
M_.exo_names_tex(10) = {'eps\_RS'};
M_.exo_names_long(10) = {'eps_RS'};
M_.exo_names(11) = {'eps_piest'};
M_.exo_names_tex(11) = {'eps\_piest'};
M_.exo_names_long(11) = {'eps_piest'};
M_.exo_names(12) = {'eps_RRst'};
M_.exo_names_tex(12) = {'eps\_RRst'};
M_.exo_names_long(12) = {'eps_RRst'};
M_.exo_names(13) = {'eps_gst'};
M_.exo_names_tex(13) = {'eps\_gst'};
M_.exo_names_long(13) = {'eps_gst'};
M_.exo_names(14) = {'eps_Rp_Fx'};
M_.exo_names_tex(14) = {'eps\_Rp\_Fx'};
M_.exo_names_long(14) = {'eps_Rp_Fx'};
M_.exo_names(15) = {'u_spread_gap'};
M_.exo_names_tex(15) = {'u\_spread\_gap'};
M_.exo_names_long(15) = {'u_spread_gap'};
M_.exo_names(16) = {'eps_zst'};
M_.exo_names_tex(16) = {'eps\_zst'};
M_.exo_names_long(16) = {'eps_zst'};
M_.exo_names(17) = {'eps_pieRPoil'};
M_.exo_names_tex(17) = {'eps\_pieRPoil'};
M_.exo_names_long(17) = {'eps_pieRPoil'};
M_.endo_names = cell(55,1);
M_.endo_names_tex = cell(55,1);
M_.endo_names_long = cell(55,1);
M_.endo_names(1) = {'ygap_row'};
M_.endo_names_tex(1) = {'\widehat{y}^{RoW}'};
M_.endo_names_long(1) = {'ygap_row'};
M_.endo_names(2) = {'dy_row'};
M_.endo_names_tex(2) = {'\Delta{y}^{RoW}'};
M_.endo_names_long(2) = {'dy_row'};
M_.endo_names(3) = {'gst_row'};
M_.endo_names_tex(3) = {'g*^{RoW}'};
M_.endo_names_long(3) = {'gst_row'};
M_.endo_names(4) = {'RR_row'};
M_.endo_names_tex(4) = {'r^{RoW}'};
M_.endo_names_long(4) = {'RR_row'};
M_.endo_names(5) = {'RRst_row'};
M_.endo_names_tex(5) = {'r*^{RoW}'};
M_.endo_names_long(5) = {'RRst_row'};
M_.endo_names(6) = {'pie_row'};
M_.endo_names_tex(6) = {'\pi^{RoW}'};
M_.endo_names_long(6) = {'pie_row'};
M_.endo_names(7) = {'pie4_row'};
M_.endo_names_tex(7) = {'\pi{4}^{RoW}'};
M_.endo_names_long(7) = {'pie4_row'};
M_.endo_names(8) = {'piest_row'};
M_.endo_names_tex(8) = {'\pi{*}^RoW'};
M_.endo_names_long(8) = {'piest_row'};
M_.endo_names(9) = {'RRgap_row'};
M_.endo_names_tex(9) = {'\widehat{r}^{RoW}'};
M_.endo_names_long(9) = {'RRgap_row'};
M_.endo_names(10) = {'i_fed'};
M_.endo_names_tex(10) = {'i^{Fed}'};
M_.endo_names_long(10) = {'i_fed'};
M_.endo_names(11) = {'ygap'};
M_.endo_names_tex(11) = {'\widehat{y}'};
M_.endo_names_long(11) = {'ygap'};
M_.endo_names(12) = {'dy'};
M_.endo_names_tex(12) = {'\Delta{y}'};
M_.endo_names_long(12) = {'dy'};
M_.endo_names(13) = {'gst'};
M_.endo_names_tex(13) = {'g^*'};
M_.endo_names_long(13) = {'gst'};
M_.endo_names(14) = {'RR'};
M_.endo_names_tex(14) = {'r'};
M_.endo_names_long(14) = {'RR'};
M_.endo_names(15) = {'RRst'};
M_.endo_names_tex(15) = {'r^n'};
M_.endo_names_long(15) = {'RRst'};
M_.endo_names(16) = {'RRst_wrong'};
M_.endo_names_tex(16) = {'RRst\_wrong'};
M_.endo_names_long(16) = {'RRst_wrong'};
M_.endo_names(17) = {'pie'};
M_.endo_names_tex(17) = {'\pi'};
M_.endo_names_long(17) = {'pie'};
M_.endo_names(18) = {'pie4'};
M_.endo_names_tex(18) = {'\pi^{4}'};
M_.endo_names_long(18) = {'pie4'};
M_.endo_names(19) = {'piest'};
M_.endo_names_tex(19) = {'\bar{\pi}'};
M_.endo_names_long(19) = {'piest'};
M_.endo_names(20) = {'RRgap'};
M_.endo_names_tex(20) = {'\widehat{r}'};
M_.endo_names_long(20) = {'RRgap'};
M_.endo_names(21) = {'i_BOI'};
M_.endo_names_tex(21) = {'i'};
M_.endo_names_long(21) = {'i_BOI'};
M_.endo_names(22) = {'z'};
M_.endo_names_tex(22) = {'z'};
M_.endo_names_long(22) = {'z'};
M_.endo_names(23) = {'zst'};
M_.endo_names_tex(23) = {'z^*'};
M_.endo_names_long(23) = {'zst'};
M_.endo_names(24) = {'zgap'};
M_.endo_names_tex(24) = {'\widehat{z}'};
M_.endo_names_long(24) = {'zgap'};
M_.endo_names(25) = {'rhost'};
M_.endo_names_tex(25) = {'\rho^{*}'};
M_.endo_names_long(25) = {'rhost'};
M_.endo_names(26) = {'dfx'};
M_.endo_names_tex(26) = {'\Delta{FX}'};
M_.endo_names_long(26) = {'dfx'};
M_.endo_names(27) = {'pie4RPoil'};
M_.endo_names_tex(27) = {'\pi{4}^{RPoil}'};
M_.endo_names_long(27) = {'pie4RPoil'};
M_.endo_names(28) = {'pieRPoil'};
M_.endo_names_tex(28) = {'\pi^{RPoil}'};
M_.endo_names_long(28) = {'pieRPoil'};
M_.endo_names(29) = {'dz'};
M_.endo_names_tex(29) = {'dz'};
M_.endo_names_long(29) = {'dz'};
M_.endo_names(30) = {'u_zst'};
M_.endo_names_tex(30) = {'u^{z^*}'};
M_.endo_names_long(30) = {'u_zst'};
M_.endo_names(31) = {'i_b'};
M_.endo_names_tex(31) = {' i^b '};
M_.endo_names_long(31) = {'i_b'};
M_.endo_names(32) = {'spread_gap'};
M_.endo_names_tex(32) = {'\widehat{\Delta}'};
M_.endo_names_long(32) = {'spread_gap'};
M_.endo_names(33) = {'B_gap'};
M_.endo_names_tex(33) = {'\widehat{b}'};
M_.endo_names_long(33) = {'B_gap'};
M_.endo_names(34) = {'cgap_b'};
M_.endo_names_tex(34) = {'\widehat{c}^b'};
M_.endo_names_long(34) = {'cgap_b'};
M_.endo_names(35) = {'BY_gap'};
M_.endo_names_tex(35) = {'\widehat{lev}'};
M_.endo_names_long(35) = {'BY_gap'};
M_.endo_names(36) = {'shock_spread_gap'};
M_.endo_names_tex(36) = {'shock\_spread\_gap'};
M_.endo_names_long(36) = {'shock_spread_gap'};
M_.endo_names(37) = {'di_BOI'};
M_.endo_names_tex(37) = {'di\_BOI'};
M_.endo_names_long(37) = {'di_BOI'};
M_.endo_names(38) = {'dygap'};
M_.endo_names_tex(38) = {'dygap'};
M_.endo_names_long(38) = {'dygap'};
M_.endo_names(39) = {'u_cbor'};
M_.endo_names_tex(39) = {'u\_cbor'};
M_.endo_names_long(39) = {'u_cbor'};
M_.endo_names(40) = {'AUX_ENDO_LEAD_394'};
M_.endo_names_tex(40) = {'AUX\_ENDO\_LEAD\_394'};
M_.endo_names_long(40) = {'AUX_ENDO_LEAD_394'};
M_.endo_names(41) = {'AUX_ENDO_LEAD_398'};
M_.endo_names_tex(41) = {'AUX\_ENDO\_LEAD\_398'};
M_.endo_names_long(41) = {'AUX_ENDO_LEAD_398'};
M_.endo_names(42) = {'AUX_ENDO_LEAD_27'};
M_.endo_names_tex(42) = {'AUX\_ENDO\_LEAD\_27'};
M_.endo_names_long(42) = {'AUX_ENDO_LEAD_27'};
M_.endo_names(43) = {'AUX_ENDO_LEAD_411'};
M_.endo_names_tex(43) = {'AUX\_ENDO\_LEAD\_411'};
M_.endo_names_long(43) = {'AUX_ENDO_LEAD_411'};
M_.endo_names(44) = {'AUX_ENDO_LEAD_415'};
M_.endo_names_tex(44) = {'AUX\_ENDO\_LEAD\_415'};
M_.endo_names_long(44) = {'AUX_ENDO_LEAD_415'};
M_.endo_names(45) = {'AUX_ENDO_LEAD_45'};
M_.endo_names_tex(45) = {'AUX\_ENDO\_LEAD\_45'};
M_.endo_names_long(45) = {'AUX_ENDO_LEAD_45'};
M_.endo_names(46) = {'AUX_ENDO_LEAD_432'};
M_.endo_names_tex(46) = {'AUX\_ENDO\_LEAD\_432'};
M_.endo_names_long(46) = {'AUX_ENDO_LEAD_432'};
M_.endo_names(47) = {'AUX_ENDO_LEAD_436'};
M_.endo_names_tex(47) = {'AUX\_ENDO\_LEAD\_436'};
M_.endo_names_long(47) = {'AUX_ENDO_LEAD_436'};
M_.endo_names(48) = {'AUX_ENDO_LEAD_137'};
M_.endo_names_tex(48) = {'AUX\_ENDO\_LEAD\_137'};
M_.endo_names_long(48) = {'AUX_ENDO_LEAD_137'};
M_.endo_names(49) = {'AUX_ENDO_LEAD_452'};
M_.endo_names_tex(49) = {'AUX\_ENDO\_LEAD\_452'};
M_.endo_names_long(49) = {'AUX_ENDO_LEAD_452'};
M_.endo_names(50) = {'AUX_ENDO_LEAD_456'};
M_.endo_names_tex(50) = {'AUX\_ENDO\_LEAD\_456'};
M_.endo_names_long(50) = {'AUX_ENDO_LEAD_456'};
M_.endo_names(51) = {'AUX_ENDO_LEAD_188'};
M_.endo_names_tex(51) = {'AUX\_ENDO\_LEAD\_188'};
M_.endo_names_long(51) = {'AUX_ENDO_LEAD_188'};
M_.endo_names(52) = {'AUX_ENDO_LAG_5_1'};
M_.endo_names_tex(52) = {'AUX\_ENDO\_LAG\_5\_1'};
M_.endo_names_long(52) = {'AUX_ENDO_LAG_5_1'};
M_.endo_names(53) = {'AUX_ENDO_LAG_5_2'};
M_.endo_names_tex(53) = {'AUX\_ENDO\_LAG\_5\_2'};
M_.endo_names_long(53) = {'AUX_ENDO_LAG_5_2'};
M_.endo_names(54) = {'AUX_ENDO_LAG_16_1'};
M_.endo_names_tex(54) = {'AUX\_ENDO\_LAG\_16\_1'};
M_.endo_names_long(54) = {'AUX_ENDO_LAG_16_1'};
M_.endo_names(55) = {'AUX_ENDO_LAG_16_2'};
M_.endo_names_tex(55) = {'AUX\_ENDO\_LAG\_16\_2'};
M_.endo_names_long(55) = {'AUX_ENDO_LAG_16_2'};
M_.endo_partitions = struct();
M_.param_names = cell(60,1);
M_.param_names_tex = cell(60,1);
M_.param_names_long = cell(60,1);
M_.param_names(1) = {'Bld_row'};
M_.param_names_tex(1) = {'Bld\_row'};
M_.param_names_long(1) = {'Bld_row'};
M_.param_names(2) = {'Blag_row'};
M_.param_names_tex(2) = {'Blag\_row'};
M_.param_names_long(2) = {'Blag_row'};
M_.param_names(3) = {'Brr_row'};
M_.param_names_tex(3) = {'Brr\_row'};
M_.param_names_long(3) = {'Brr_row'};
M_.param_names(4) = {'Apld_row'};
M_.param_names_tex(4) = {'Apld\_row'};
M_.param_names_long(4) = {'Apld_row'};
M_.param_names(5) = {'Aygap_row'};
M_.param_names_tex(5) = {'Aygap\_row'};
M_.param_names_long(5) = {'Aygap_row'};
M_.param_names(6) = {'Glag_row'};
M_.param_names_tex(6) = {'Glag\_row'};
M_.param_names_long(6) = {'Glag_row'};
M_.param_names(7) = {'Gpie_row'};
M_.param_names_tex(7) = {'Gpie\_row'};
M_.param_names_long(7) = {'Gpie_row'};
M_.param_names(8) = {'Gygap_row'};
M_.param_names_tex(8) = {'Gygap\_row'};
M_.param_names_long(8) = {'Gygap_row'};
M_.param_names(9) = {'Lp_row'};
M_.param_names_tex(9) = {'Lp\_row'};
M_.param_names_long(9) = {'Lp_row'};
M_.param_names(10) = {'pieBAR_row'};
M_.param_names_tex(10) = {'pieBAR\_row'};
M_.param_names_long(10) = {'pieBAR_row'};
M_.param_names(11) = {'Lrr_row'};
M_.param_names_tex(11) = {'Lrr\_row'};
M_.param_names_long(11) = {'Lrr_row'};
M_.param_names(12) = {'rrBAR_row'};
M_.param_names_tex(12) = {'rrBAR\_row'};
M_.param_names_long(12) = {'rrBAR_row'};
M_.param_names(13) = {'Lg_row'};
M_.param_names_tex(13) = {'Lg\_row'};
M_.param_names_long(13) = {'Lg_row'};
M_.param_names(14) = {'gBAR_row'};
M_.param_names_tex(14) = {'gBAR\_row'};
M_.param_names_long(14) = {'gBAR_row'};
M_.param_names(15) = {'Bld'};
M_.param_names_tex(15) = {'Bld'};
M_.param_names_long(15) = {'Bld'};
M_.param_names(16) = {'Blag'};
M_.param_names_tex(16) = {'Blag'};
M_.param_names_long(16) = {'Blag'};
M_.param_names(17) = {'Brr'};
M_.param_names_tex(17) = {'Brr'};
M_.param_names_long(17) = {'Brr'};
M_.param_names(18) = {'Bzgap'};
M_.param_names_tex(18) = {'Bzgap'};
M_.param_names_long(18) = {'Bzgap'};
M_.param_names(19) = {'Byrow'};
M_.param_names_tex(19) = {'Byrow'};
M_.param_names_long(19) = {'Byrow'};
M_.param_names(20) = {'Brr_b_factor'};
M_.param_names_tex(20) = {'Brr\_b\_factor'};
M_.param_names_long(20) = {'Brr_b_factor'};
M_.param_names(21) = {'Apld'};
M_.param_names_tex(21) = {'Apld'};
M_.param_names_long(21) = {'Apld'};
M_.param_names(22) = {'Aygap'};
M_.param_names_tex(22) = {'Aygap'};
M_.param_names_long(22) = {'Aygap'};
M_.param_names(23) = {'Az'};
M_.param_names_tex(23) = {'Az'};
M_.param_names_long(23) = {'Az'};
M_.param_names(24) = {'A0'};
M_.param_names_tex(24) = {'A0'};
M_.param_names_long(24) = {'A0'};
M_.param_names(25) = {'A1'};
M_.param_names_tex(25) = {'A1'};
M_.param_names_long(25) = {'A1'};
M_.param_names(26) = {'Glag'};
M_.param_names_tex(26) = {'Glag'};
M_.param_names_long(26) = {'Glag'};
M_.param_names(27) = {'Gpie'};
M_.param_names_tex(27) = {'Gpie'};
M_.param_names_long(27) = {'Gpie'};
M_.param_names(28) = {'Gygap'};
M_.param_names_tex(28) = {'Gygap'};
M_.param_names_long(28) = {'Gygap'};
M_.param_names(29) = {'Gfx'};
M_.param_names_tex(29) = {'Gfx'};
M_.param_names_long(29) = {'Gfx'};
M_.param_names(30) = {'Lp'};
M_.param_names_tex(30) = {'Lp'};
M_.param_names_long(30) = {'Lp'};
M_.param_names(31) = {'pieBAR'};
M_.param_names_tex(31) = {'pieBAR'};
M_.param_names_long(31) = {'pieBAR'};
M_.param_names(32) = {'Lrr'};
M_.param_names_tex(32) = {'Lrr'};
M_.param_names_long(32) = {'Lrr'};
M_.param_names(33) = {'rrBAR'};
M_.param_names_tex(33) = {'rrBAR'};
M_.param_names_long(33) = {'rrBAR'};
M_.param_names(34) = {'Lg'};
M_.param_names_tex(34) = {'Lg'};
M_.param_names_long(34) = {'Lg'};
M_.param_names(35) = {'gBAR'};
M_.param_names_tex(35) = {'gBAR'};
M_.param_names_long(35) = {'gBAR'};
M_.param_names(36) = {'Loil'};
M_.param_names_tex(36) = {'Loil'};
M_.param_names_long(36) = {'Loil'};
M_.param_names(37) = {'Ls_row'};
M_.param_names_tex(37) = {'Ls\_row'};
M_.param_names_long(37) = {'Ls_row'};
M_.param_names(38) = {'sprBAR_row'};
M_.param_names_tex(38) = {'sprBAR\_row'};
M_.param_names_long(38) = {'sprBAR_row'};
M_.param_names(39) = {'Ls'};
M_.param_names_tex(39) = {'Ls'};
M_.param_names_long(39) = {'Ls'};
M_.param_names(40) = {'sprBAR'};
M_.param_names_tex(40) = {'sprBAR'};
M_.param_names_long(40) = {'sprBAR'};
M_.param_names(41) = {'Dz'};
M_.param_names_tex(41) = {'Dz'};
M_.param_names_long(41) = {'Dz'};
M_.param_names(42) = {'Lz'};
M_.param_names_tex(42) = {'Lz'};
M_.param_names_long(42) = {'Lz'};
M_.param_names(43) = {'zBAR'};
M_.param_names_tex(43) = {'zBAR'};
M_.param_names_long(43) = {'zBAR'};
M_.param_names(44) = {'vRPoil'};
M_.param_names_tex(44) = {'vRPoil'};
M_.param_names_long(44) = {'vRPoil'};
M_.param_names(45) = {'Luz'};
M_.param_names_tex(45) = {'Luz'};
M_.param_names_long(45) = {'Luz'};
M_.param_names(46) = {'par_ystar'};
M_.param_names_tex(46) = {'par\_ystar'};
M_.param_names_long(46) = {'par_ystar'};
M_.param_names(47) = {'par_Eqr'};
M_.param_names_tex(47) = {'par\_Eqr'};
M_.param_names_long(47) = {'par_Eqr'};
M_.param_names(48) = {'alfa2_row'};
M_.param_names_tex(48) = {'alfa2\_row'};
M_.param_names_long(48) = {'alfa2_row'};
M_.param_names(49) = {'alfa1_row'};
M_.param_names_tex(49) = {'alfa1\_row'};
M_.param_names_long(49) = {'alfa1_row'};
M_.param_names(50) = {'alfa1'};
M_.param_names_tex(50) = {'alfa1'};
M_.param_names_long(50) = {'alfa1'};
M_.param_names(51) = {'alfa2'};
M_.param_names_tex(51) = {'alfa2'};
M_.param_names_long(51) = {'alfa2'};
M_.param_names(52) = {'alfa3'};
M_.param_names_tex(52) = {'alfa3'};
M_.param_names_long(52) = {'alfa3'};
M_.param_names(53) = {'alfa4'};
M_.param_names_tex(53) = {'alfa4'};
M_.param_names_long(53) = {'alfa4'};
M_.param_names(54) = {'alfa5'};
M_.param_names_tex(54) = {'alfa5'};
M_.param_names_long(54) = {'alfa5'};
M_.param_names(55) = {'p_spr_lev'};
M_.param_names_tex(55) = {'p\_spr\_lev'};
M_.param_names_long(55) = {'p_spr_lev'};
M_.param_names(56) = {'p_rho_spread'};
M_.param_names_tex(56) = {'p\_rho\_spread'};
M_.param_names_long(56) = {'p_rho_spread'};
M_.param_names(57) = {'par_b1'};
M_.param_names_tex(57) = {'par\_b1'};
M_.param_names_long(57) = {'par_b1'};
M_.param_names(58) = {'par_b2'};
M_.param_names_tex(58) = {'par\_b2'};
M_.param_names_long(58) = {'par_b2'};
M_.param_names(59) = {'par_v'};
M_.param_names_tex(59) = {'par\_v'};
M_.param_names_long(59) = {'par_v'};
M_.param_names(60) = {'par_flag'};
M_.param_names_tex(60) = {'par\_flag'};
M_.param_names_long(60) = {'par_flag'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 17;
M_.endo_nbr = 55;
M_.param_nbr = 60;
M_.orig_endo_nbr = 39;
M_.aux_vars(1).endo_index = 40;
M_.aux_vars(1).type = 0;
M_.aux_vars(1).orig_expr = 'pie4_row(1)';
M_.aux_vars(2).endo_index = 41;
M_.aux_vars(2).type = 0;
M_.aux_vars(2).orig_expr = 'AUX_ENDO_LEAD_394(1)';
M_.aux_vars(3).endo_index = 42;
M_.aux_vars(3).type = 0;
M_.aux_vars(3).orig_expr = 'AUX_ENDO_LEAD_398(1)';
M_.aux_vars(4).endo_index = 43;
M_.aux_vars(4).type = 0;
M_.aux_vars(4).orig_expr = 'piest_row(1)';
M_.aux_vars(5).endo_index = 44;
M_.aux_vars(5).type = 0;
M_.aux_vars(5).orig_expr = 'AUX_ENDO_LEAD_411(1)';
M_.aux_vars(6).endo_index = 45;
M_.aux_vars(6).type = 0;
M_.aux_vars(6).orig_expr = 'AUX_ENDO_LEAD_415(1)';
M_.aux_vars(7).endo_index = 46;
M_.aux_vars(7).type = 0;
M_.aux_vars(7).orig_expr = 'pie4(1)';
M_.aux_vars(8).endo_index = 47;
M_.aux_vars(8).type = 0;
M_.aux_vars(8).orig_expr = 'AUX_ENDO_LEAD_432(1)';
M_.aux_vars(9).endo_index = 48;
M_.aux_vars(9).type = 0;
M_.aux_vars(9).orig_expr = 'AUX_ENDO_LEAD_436(1)';
M_.aux_vars(10).endo_index = 49;
M_.aux_vars(10).type = 0;
M_.aux_vars(10).orig_expr = 'piest(1)';
M_.aux_vars(11).endo_index = 50;
M_.aux_vars(11).type = 0;
M_.aux_vars(11).orig_expr = 'AUX_ENDO_LEAD_452(1)';
M_.aux_vars(12).endo_index = 51;
M_.aux_vars(12).type = 0;
M_.aux_vars(12).orig_expr = 'AUX_ENDO_LEAD_456(1)';
M_.aux_vars(13).endo_index = 52;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 6;
M_.aux_vars(13).orig_lead_lag = -1;
M_.aux_vars(13).orig_expr = 'pie_row(-1)';
M_.aux_vars(14).endo_index = 53;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 6;
M_.aux_vars(14).orig_lead_lag = -2;
M_.aux_vars(14).orig_expr = 'AUX_ENDO_LAG_5_1(-1)';
M_.aux_vars(15).endo_index = 54;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 17;
M_.aux_vars(15).orig_lead_lag = -1;
M_.aux_vars(15).orig_expr = 'pie(-1)';
M_.aux_vars(16).endo_index = 55;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 17;
M_.aux_vars(16).orig_lead_lag = -2;
M_.aux_vars(16).orig_expr = 'AUX_ENDO_LAG_16_1(-1)';
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(17, 17);
M_.Correlation_matrix = eye(17, 17);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.orig_eq_nbr = 39;
M_.eq_nbr = 55;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 3;
M_.orig_maximum_endo_lead = 4;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 3;
M_.orig_maximum_lead = 4;
M_.orig_maximum_lag_with_diffs_expanded = 3;
M_.lead_lag_incidence = [
 1 27 82;
 0 28 83;
 2 29 84;
 0 30 0;
 0 31 0;
 3 32 85;
 4 33 86;
 5 34 87;
 6 35 0;
 7 36 0;
 8 37 88;
 0 38 0;
 9 39 89;
 0 40 0;
 0 41 0;
 0 42 0;
 10 43 90;
 11 44 91;
 12 45 92;
 13 46 0;
 14 47 0;
 15 48 93;
 16 49 94;
 17 50 0;
 0 51 0;
 0 52 0;
 0 53 0;
 18 54 0;
 0 55 0;
 19 56 0;
 0 57 0;
 0 58 0;
 20 59 0;
 21 60 95;
 0 61 0;
 22 62 0;
 0 63 0;
 0 64 0;
 0 65 96;
 0 66 97;
 0 67 98;
 0 68 99;
 0 69 100;
 0 70 101;
 0 71 102;
 0 72 103;
 0 73 104;
 0 74 105;
 0 75 106;
 0 76 107;
 0 77 108;
 23 78 0;
 24 79 0;
 25 80 0;
 26 81 0;]';
M_.nstatic = 15;
M_.nfwrd   = 14;
M_.npred   = 13;
M_.nboth   = 13;
M_.nsfwrd   = 27;
M_.nspred   = 26;
M_.ndynamic   = 40;
M_.dynamic_tmp_nbr = [0; 0; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'ygap_row' ;
  2 , 'name' , 'pie_row' ;
  3 , 'name' , 'i_fed' ;
  4 , 'name' , 'piest_row' ;
  5 , 'name' , 'RRst_row' ;
  6 , 'name' , 'gst_row' ;
  7 , 'name' , 'RRgap_row' ;
  8 , 'name' , 'pie4_row' ;
  9 , 'name' , 'RR_row' ;
  10 , 'name' , 'dy_row' ;
  11 , 'name' , 'ygap' ;
  12 , 'name' , 'pie' ;
  13 , 'name' , 'z' ;
  14 , 'name' , 'i_BOI' ;
  15 , 'name' , 'di_BOI' ;
  16 , 'name' , 'dygap' ;
  17 , 'name' , 'piest' ;
  18 , 'name' , 'RRst' ;
  19 , 'name' , 'RRst_wrong' ;
  20 , 'name' , 'gst' ;
  21 , 'name' , 'rhost' ;
  22 , 'name' , 'zst' ;
  23 , 'name' , 'u_zst' ;
  24 , 'name' , 'pieRPoil' ;
  25 , 'name' , 'RRgap' ;
  26 , 'name' , 'pie4' ;
  27 , 'name' , 'RR' ;
  28 , 'name' , 'zgap' ;
  29 , 'name' , 'dfx' ;
  30 , 'name' , 'dy' ;
  31 , 'name' , 'pie4RPoil' ;
  32 , 'name' , 'dz' ;
  33 , 'name' , 'spread_gap' ;
  34 , 'name' , 'shock_spread_gap' ;
  35 , 'name' , 'BY_gap' ;
  36 , 'name' , 'i_b' ;
  37 , 'name' , 'B_gap' ;
  38 , 'name' , 'cgap_b' ;
  39 , 'name' , 'u_cbor' ;
};
M_.mapping.ygap_row.eqidx = [1 2 3 10 11 ];
M_.mapping.dy_row.eqidx = [10 18 19 20 ];
M_.mapping.gst_row.eqidx = [5 6 10 ];
M_.mapping.RR_row.eqidx = [7 9 13 ];
M_.mapping.RRst_row.eqidx = [3 5 7 21 ];
M_.mapping.pie_row.eqidx = [2 8 9 29 ];
M_.mapping.pie4_row.eqidx = [2 3 8 ];
M_.mapping.piest_row.eqidx = [3 4 ];
M_.mapping.RRgap_row.eqidx = [1 7 ];
M_.mapping.i_fed.eqidx = [3 9 ];
M_.mapping.ygap.eqidx = [11 12 14 30 35 37 ];
M_.mapping.dy.eqidx = [16 30 ];
M_.mapping.gst.eqidx = [16 18 19 20 30 37 38 ];
M_.mapping.RR.eqidx = [13 25 27 ];
M_.mapping.RRst.eqidx = [14 18 21 25 ];
M_.mapping.RRst_wrong.eqidx = [14 19 ];
M_.mapping.pie.eqidx = [12 26 27 29 37 38 ];
M_.mapping.pie4.eqidx = [12 14 26 ];
M_.mapping.piest.eqidx = [14 17 ];
M_.mapping.RRgap.eqidx = [11 25 ];
M_.mapping.i_BOI.eqidx = [14 15 27 36 ];
M_.mapping.z.eqidx = [13 28 29 32 ];
M_.mapping.zst.eqidx = [20 21 22 28 ];
M_.mapping.zgap.eqidx = [11 28 ];
M_.mapping.rhost.eqidx = [13 21 ];
M_.mapping.dfx.eqidx = [29 ];
M_.mapping.pie4RPoil.eqidx = [31 ];
M_.mapping.pieRPoil.eqidx = [12 24 ];
M_.mapping.dz.eqidx = [12 14 32 ];
M_.mapping.u_zst.eqidx = [22 23 ];
M_.mapping.i_b.eqidx = [36 37 38 ];
M_.mapping.spread_gap.eqidx = [18 33 36 ];
M_.mapping.B_gap.eqidx = [35 37 ];
M_.mapping.cgap_b.eqidx = [37 38 ];
M_.mapping.BY_gap.eqidx = [33 35 38 ];
M_.mapping.shock_spread_gap.eqidx = [33 34 ];
M_.mapping.di_BOI.eqidx = [15 ];
M_.mapping.dygap.eqidx = [16 ];
M_.mapping.u_cbor.eqidx = [18 38 39 ];
M_.mapping.eps_ygap_row.eqidx = [1 ];
M_.mapping.eps_pie_row.eqidx = [2 ];
M_.mapping.eps_RS_row.eqidx = [3 ];
M_.mapping.eps_piest_row.eqidx = [4 ];
M_.mapping.eps_RRst_row.eqidx = [5 ];
M_.mapping.eps_gst_row.eqidx = [6 ];
M_.mapping.eps_cb.eqidx = [39 ];
M_.mapping.eps_ygap.eqidx = [11 ];
M_.mapping.eps_pie.eqidx = [12 ];
M_.mapping.eps_RS.eqidx = [14 ];
M_.mapping.eps_piest.eqidx = [17 ];
M_.mapping.eps_RRst.eqidx = [18 19 ];
M_.mapping.eps_gst.eqidx = [20 ];
M_.mapping.eps_Rp_Fx.eqidx = [21 ];
M_.mapping.u_spread_gap.eqidx = [34 ];
M_.mapping.eps_zst.eqidx = [23 ];
M_.mapping.eps_pieRPoil.eqidx = [24 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [1 3 6 7 8 9 10 11 13 17 18 19 20 21 22 23 24 28 30 33 34 36 52 53 54 55 ];
M_.exo_names_orig_ord = [1:17];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(55, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(17, 1);
M_.params = NaN(60, 1);
M_.endo_trends = struct('deflator', cell(55, 1), 'log_deflator', cell(55, 1), 'growth_factor', cell(55, 1), 'log_growth_factor', cell(55, 1));
M_.NNZDerivatives = [202; -1; -1; ];
M_.static_tmp_nbr = [0; 0; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
M_.params(1) = 0.3873;
Bld_row = M_.params(1);
M_.params(2) = 0.7737;
Blag_row = M_.params(2);
M_.params(3) = 0.0984;
Brr_row = M_.params(3);
M_.params(15) = 0.4523;
Bld = M_.params(15);
M_.params(16) = 1-M_.params(15);
Blag = M_.params(16);
M_.params(17) = 0.1;
Brr = M_.params(17);
M_.params(20) = 5;
Brr_b_factor = M_.params(20);
M_.params(18) = 0.0033;
Bzgap = M_.params(18);
M_.params(19) = 0.0254;
Byrow = M_.params(19);
M_.params(4) = 0.7111;
Apld_row = M_.params(4);
M_.params(5) = 0.1028;
Aygap_row = M_.params(5);
M_.params(21) = 0.5864;
Apld = M_.params(21);
M_.params(22) = 0.1172;
Aygap = M_.params(22);
M_.params(23) = 0.0727;
Az = M_.params(23);
M_.params(24) = 0.0146;
A0 = M_.params(24);
M_.params(25) = 0;
A1 = M_.params(25);
M_.params(6) = 0.8994;
Glag_row = M_.params(6);
M_.params(7) = 1.4985;
Gpie_row = M_.params(7);
M_.params(8) = 0.3033;
Gygap_row = M_.params(8);
M_.params(26) = 0.8448;
Glag = M_.params(26);
M_.params(27) = 1.8315;
Gpie = M_.params(27);
M_.params(28) = 0.4480;
Gygap = M_.params(28);
M_.params(29) = 0.00;
Gfx = M_.params(29);
M_.params(41) = 0.6180;
Dz = M_.params(41);
M_.params(42) = 0.7999999999999999;
Lz = M_.params(42);
M_.params(43) = 0.00;
zBAR = M_.params(43);
M_.params(45) = 0.999;
Luz = M_.params(45);
M_.params(9) = 0.95;
Lp_row = M_.params(9);
M_.params(11) = 0.96;
Lrr_row = M_.params(11);
M_.params(13) = 0.95;
Lg_row = M_.params(13);
M_.params(10) = 2.00;
pieBAR_row = M_.params(10);
M_.params(12) = 3.00;
rrBAR_row = M_.params(12);
M_.params(14) = 0.45;
gBAR_row = M_.params(14);
M_.params(30) = 0.8;
Lp = M_.params(30);
M_.params(32) = 0.97;
Lrr = M_.params(32);
M_.params(34) = 0.95;
Lg = M_.params(34);
M_.params(36) = 0.15;
Loil = M_.params(36);
M_.params(31) = 2.00;
pieBAR = M_.params(31);
M_.params(33) = 3.00;
rrBAR = M_.params(33);
M_.params(35) = 0.45;
gBAR = M_.params(35);
M_.params(44) = 0;
vRPoil = M_.params(44);
M_.params(37) = 0.85;
Ls_row = M_.params(37);
M_.params(38) = 0;
sprBAR_row = M_.params(38);
M_.params(39) = 0.80;
Ls = M_.params(39);
M_.params(40) = 0;
sprBAR = M_.params(40);
M_.params(48) = 1;
alfa2_row = M_.params(48);
M_.params(49) = M_.params(12)-4*M_.params(48)*M_.params(14);
alfa1_row = M_.params(49);
M_.params(57) = 0.6;
par_b1 = M_.params(57);
M_.params(58) = 0.8;
par_b2 = M_.params(58);
M_.params(59) = 0.225;
par_v = M_.params(59);
M_.params(47) = 0.1;
par_Eqr = M_.params(47);
M_.params(46) = 0.1;
par_ystar = M_.params(46);
M_.params(55) = 0.031;
p_spr_lev = M_.params(55);
M_.params(56) = 0.7;
p_rho_spread = M_.params(56);
M_.params(51) = 0.4;
alfa2 = M_.params(51);
M_.params(52) = 0.6;
alfa3 = M_.params(52);
M_.params(53) = 0.5;
alfa4 = M_.params(53);
M_.params(54) = 0.2;
alfa5 = M_.params(54);
spread_gap_SS=0; 
M_.params(50) = M_.params(33)-4*M_.params(51)*M_.params(35)-M_.params(14)*4*M_.params(52)+M_.params(53)*spread_gap_SS;
alfa1 = M_.params(50);
M_.params(60) = 0;
par_flag = M_.params(60);
%
% INITVAL instructions
%
options_.initval_file = false;
oo_.steady_state(1) = 0;
oo_.steady_state(6) = M_.params(10);
oo_.steady_state(10) = M_.params(12)+M_.params(10);
oo_.steady_state(8) = M_.params(10);
oo_.steady_state(5) = M_.params(12);
oo_.steady_state(9) = 0;
oo_.steady_state(7) = M_.params(10);
oo_.steady_state(4) = M_.params(12);
oo_.steady_state(3) = M_.params(14);
oo_.steady_state(2) = M_.params(14);
oo_.steady_state(11) = 0;
oo_.steady_state(17) = M_.params(31);
oo_.steady_state(19) = M_.params(31);
oo_.steady_state(15) = M_.params(33);
oo_.steady_state(16) = M_.params(33);
oo_.steady_state(20) = 0;
oo_.steady_state(18) = M_.params(31);
oo_.steady_state(14) = M_.params(33);
oo_.steady_state(13) = M_.params(35);
oo_.steady_state(12) = M_.params(35);
oo_.steady_state(22) = 0;
oo_.steady_state(23) = 0;
oo_.steady_state(24) = 0;
oo_.steady_state(25) = M_.params(33)-M_.params(12)-M_.params(38);
oo_.steady_state(23) = 0;
oo_.steady_state(26) = (M_.params(31)-M_.params(10))/4;
oo_.steady_state(21) = M_.params(33)+M_.params(31);
oo_.steady_state(27) = 0;
oo_.steady_state(36) = 0;
oo_.steady_state(40)=oo_.steady_state(7);
oo_.steady_state(41)=oo_.steady_state(40);
oo_.steady_state(42)=oo_.steady_state(41);
oo_.steady_state(43)=oo_.steady_state(8);
oo_.steady_state(44)=oo_.steady_state(43);
oo_.steady_state(45)=oo_.steady_state(44);
oo_.steady_state(46)=oo_.steady_state(18);
oo_.steady_state(47)=oo_.steady_state(46);
oo_.steady_state(48)=oo_.steady_state(47);
oo_.steady_state(49)=oo_.steady_state(19);
oo_.steady_state(50)=oo_.steady_state(49);
oo_.steady_state(51)=oo_.steady_state(50);
oo_.steady_state(52)=oo_.steady_state(6);
oo_.steady_state(53)=oo_.steady_state(52);
oo_.steady_state(54)=oo_.steady_state(17);
oo_.steady_state(55)=oo_.steady_state(54);
if M_.exo_nbr > 0
	oo_.exo_simul = ones(M_.maximum_lag,1)*oo_.exo_steady_state';
end
if M_.exo_det_nbr > 0
	oo_.exo_det_simul = ones(M_.maximum_lag,1)*oo_.exo_det_steady_state';
end
steady;
oo_.dr.eigval = check(M_,options_,oo_);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(7, 7) = (5.03)^2;
M_.Sigma_e(8, 8) = (0.4106)^2;
M_.Sigma_e(9, 9) = (1.9)^2;
M_.Sigma_e(10, 10) = (0.20)^2;
M_.Sigma_e(13, 13) = (0.20)^2;
M_.Sigma_e(14, 14) = (0.3290)^2;
M_.Sigma_e(15, 15) = (0.4)^2;
disp('Sensativity_index');
1
Vec_p_spr_lev   = [0.031, 0.031, 0.031]; 
Vec_p_NRI_Spr   = [0.5  , 0.5   , 0.5]  ;
Vec_p_NRI_PrefShock   = [0.2  , 0.2   , 0.2]  ;		 
Vec_p_yGap_rGap = [0.1  , 0.1   , 0.1]  ;       
Vec_p_Brr_b_factor= [5  , 5     , 5]    ;       
Vec_par_v       =  1 * [0.0225, 0.0225, 0.0225];       
Vec_par_flag=     [0,0,0];
FileNamePrefix = 'elasticity_Spr_Lev_';     
Vec_p_spr_lev   = [0, 0.031, 0.1] ; 
LegendSTR   = {'Original','MP' } ;   
LegendSTR = buildLegend('$\beta^{\Delta}_{lev}=','$',Vec_p_spr_lev)   
FileNameValue = Vec_p_spr_lev ;
loss_Version1=[];
loss_Version2=[];
loss_Version3=[];
loss_Version4=[];
disp(['Simulation number: ',num2str(1)]);
M_.params(55) = Vec_p_spr_lev(1);
p_spr_lev = M_.params(55);
M_.params(53) = Vec_p_NRI_Spr(1);
alfa4 = M_.params(53);
M_.params(54) = Vec_p_NRI_PrefShock(1);
alfa5 = M_.params(54);
M_.params(17) = Vec_p_yGap_rGap(1);
Brr = M_.params(17);
M_.params(20) = Vec_p_Brr_b_factor(1);
Brr_b_factor = M_.params(20);
M_.params(59) = Vec_par_v(1);
par_v = M_.params(59);
M_.params(60) = Vec_par_flag(1);
par_flag = M_.params(60);
M_.params(50) = M_.params(33)-4*M_.params(51)*M_.params(35)-M_.params(14)*4*M_.params(52)+M_.params(53)*spread_gap_SS;
alfa1 = M_.params(50);
disp([p_spr_lev, par_v, alfa4, alfa5]);
steady;
oo_.dr.eigval = check(M_,options_,oo_);
options_.irf = 20;
options_.nocorr = true;
options_.nofunctions = true;
options_.nograph = true;
options_.order = 1;
options_.periods = 0;
var_list_ = {'ygap';'i_BOI';'pie';'BY_gap';'spread_gap';'RRst';'cgap_b';'z';'i_b'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);
loss_Version1=[loss_Version1, oo_.var(4,4)+0.5*oo_.var(2,2)+6*oo_.var(5,5)]; 
loss_Version2=[loss_Version2, oo_.var(4,4)+0.5*oo_.var(6,6)+6*oo_.var(5,5)];
loss_Version3=[loss_Version3, oo_.var(4,4)+0.5*oo_.var(2,2)];                 
loss_Version4=[loss_Version4, oo_.var(4,4)+0.5*oo_.var(6,6)];                 
MultiOO{1}=oo_; 
filename = ['IRFs_',FileNamePrefix,num2str(FileNameValue(1)),'.xlsx']
disp(['Simulation number: ',num2str(2)]);
M_.params(55) = Vec_p_spr_lev(2);
p_spr_lev = M_.params(55);
M_.params(53) = Vec_p_NRI_Spr(2);
alfa4 = M_.params(53);
M_.params(54) = Vec_p_NRI_PrefShock(2);
alfa5 = M_.params(54);
M_.params(17) = Vec_p_yGap_rGap(2);
Brr = M_.params(17);
M_.params(20) = Vec_p_Brr_b_factor(2);
Brr_b_factor = M_.params(20);
M_.params(59) = Vec_par_v(2);
par_v = M_.params(59);
M_.params(60) = Vec_par_flag(2);
par_flag = M_.params(60);
M_.params(50) = M_.params(33)-4*M_.params(51)*M_.params(35)-M_.params(14)*4*M_.params(52)+M_.params(53)*spread_gap_SS;
alfa1 = M_.params(50);
disp([p_spr_lev, par_v, alfa4, alfa5]);
steady;
oo_.dr.eigval = check(M_,options_,oo_);
options_.irf = 20;
options_.nocorr = true;
options_.nofunctions = true;
options_.nograph = true;
options_.order = 1;
options_.periods = 0;
var_list_ = {'ygap';'i_BOI';'pie';'BY_gap';'spread_gap';'RRst';'cgap_b';'z';'i_b'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);
loss_Version1=[loss_Version1, oo_.var(4,4)+0.5*oo_.var(2,2)+6*oo_.var(5,5)]; 
loss_Version2=[loss_Version2, oo_.var(4,4)+0.5*oo_.var(6,6)+6*oo_.var(5,5)];
loss_Version3=[loss_Version3, oo_.var(4,4)+0.5*oo_.var(2,2)];                 
loss_Version4=[loss_Version4, oo_.var(4,4)+0.5*oo_.var(6,6)];                 
MultiOO{2}=oo_; 
filename = ['IRFs_',FileNamePrefix,num2str(FileNameValue(2)),'.xlsx']
disp(['Simulation number: ',num2str(3)]);
M_.params(55) = Vec_p_spr_lev(3);
p_spr_lev = M_.params(55);
M_.params(53) = Vec_p_NRI_Spr(3);
alfa4 = M_.params(53);
M_.params(54) = Vec_p_NRI_PrefShock(3);
alfa5 = M_.params(54);
M_.params(17) = Vec_p_yGap_rGap(3);
Brr = M_.params(17);
M_.params(20) = Vec_p_Brr_b_factor(3);
Brr_b_factor = M_.params(20);
M_.params(59) = Vec_par_v(3);
par_v = M_.params(59);
M_.params(60) = Vec_par_flag(3);
par_flag = M_.params(60);
M_.params(50) = M_.params(33)-4*M_.params(51)*M_.params(35)-M_.params(14)*4*M_.params(52)+M_.params(53)*spread_gap_SS;
alfa1 = M_.params(50);
disp([p_spr_lev, par_v, alfa4, alfa5]);
steady;
oo_.dr.eigval = check(M_,options_,oo_);
options_.irf = 20;
options_.nocorr = true;
options_.nofunctions = true;
options_.nograph = true;
options_.order = 1;
options_.periods = 0;
var_list_ = {'ygap';'i_BOI';'pie';'BY_gap';'spread_gap';'RRst';'cgap_b';'z';'i_b'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);
loss_Version1=[loss_Version1, oo_.var(4,4)+0.5*oo_.var(2,2)+6*oo_.var(5,5)]; 
loss_Version2=[loss_Version2, oo_.var(4,4)+0.5*oo_.var(6,6)+6*oo_.var(5,5)];
loss_Version3=[loss_Version3, oo_.var(4,4)+0.5*oo_.var(2,2)];                 
loss_Version4=[loss_Version4, oo_.var(4,4)+0.5*oo_.var(6,6)];                 
MultiOO{3}=oo_; 
filename = ['IRFs_',FileNamePrefix,num2str(FileNameValue(3)),'.xlsx']
addpath('Lib_MultiSim') ;
Formats = {'png'};
v_colors    = [];           
v_style     = { ':','--','-','--',':'}; 
v_width     = [ 1.6, 1.8, 2, 1.6];
LegendAT    =  [6,1,3,0,0,8,9,9,9,9,9];  
MultiIRFs( M_, MultiOO, var_list_, options_, LegendAT, LegendSTR ,v_colors ,v_style , v_width, Formats,FileNamePrefix);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'QPMwCredit_24_5_22_nim_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'QPMwCredit_24_5_22_nim_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'QPMwCredit_24_5_22_nim_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'QPMwCredit_24_5_22_nim_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'QPMwCredit_24_5_22_nim_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'QPMwCredit_24_5_22_nim_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'QPMwCredit_24_5_22_nim_results.mat'], 'oo_recursive_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
