    
%  'RL', 'ratio_ho_hr_tag', 'ratio_hoa_hra' ,'h_alt', 'w', 'w_tag', 'N', 'h_cost'
%  'Lp_m'  % renters MC
%	'r_q_ratio'

% in percentile change (from SS):
% for MP shock
Varibels_4_4 = {'LY','DP_cpi_a','r_CB_a', 'R_a',...
				'DP_r_a', 'Lr', 'Lq', 'ltv', ...
				'L_h_inv','Lh_o',  'Lh_r','LC',...
				'LB_tag','Lh_o_tag','Lh_r_tag','LC_tag'};


% for LTV shock
% Varibels_4_4 = {'LY','DP_cpi_a','r_CB_a', 'R_a',...
% 				'DP_r_a', 'Lr', 'Lq', 'ltv', ...
% 				'L_h_inv','Lh_o',  'Lh_r','LC',...
% 				'LB_tag','Lh_o_tag','Lh_r_tag','LC_tag'};
% 

Varibels_Agg_2_3 = {	'r_CB_a', 'DP_a', ...
						'R_a',	 'DP_r_a',...  
						'LY',	'Lq'};
Varibels_TANK_3_3 = { 	'Lh_r_tag','Lh_r', 'L_h_inv', ...
					'Lh_o_tag', 'Lh_o', 'Lr',... 
					'LC_tag' , 'LC', 'Lrqratio'	};
% {'eps_h'} {'eps_CB'}  {'eps_ltv'}
   

irfs_models_d({model_default,model_Ltv_tight}, 0, Varibels_Agg_4_4, {'eps_CB'});
%irfs_models_d({model_default,model_low_sub_o_r}, 0, Varibels_Aggregate, {'eps_CB'});
%irfs_models_d({model_default}, 0, Varibels_4_4, {'eps_ltv'});
