clear
close all
addpath('functions')
model_default = combine_mods({'A_Declaration.mod','B_Calibration.mod','C_Model.mod',...
                              'D_SS.mod','E_Shocks.mod','F_Irfs.mod'},...
                              'Baseline.mod');    
% model_low_sub_o_r = combine_mods({'A_Declaration.mod','B_Calibration_low_sub_o_r.mod','C_Model.mod',...
								%'D_SS.mod','E_Shocks.mod','F_Irfs.mod'},...
%                               'low_sub_o_r.mod');    
model_Ltv_tight = combine_mods({'A_Declaration.mod','B_Calibration_Ltv_tight.mod','C_Model.mod',...
                                'D_SS.mod','E_Shocks.mod','F_Irfs.mod'},...
                                'Ltv_tight.mod');                               

model_Ltv_tight_partial = combine_mods({'A_Declaration.mod','B_Calibration_Ltv_tight_partial.mod','C_Model.mod',...
                                'D_SS.mod','E_Shocks.mod','F_Irfs.mod'},...
                                'Ltv_tight_partial.mod');                               

% model_wo_rent_rig = combine_mods({'A_Declaration.mod','B_Calibration_wo_rent_rig.mod','C_Model.mod','D_SS.mod',...
%                              'E_Shocks.mod','F_Irfs.mod'},...
%                              'wo_rent_rig.mod');                               
