clear
close all

% add 'functions' folder located in parent directory of current folder
parentFunctions = fullfile(fileparts(pwd), 'functions');
if exist(parentFunctions, 'dir')
    addpath(parentFunctions);
else
    error('Parent-level ''functions'' folder not found at: %s', parentFunctions);
end


Baseline = combine_mods({'A_Declaration.mod','B_Calibration_005.mod','C_Model.mod',...
                              'D_SS.mod','E_Shocks.mod','F_Irfs.mod'},...
                              'Baseline.mod'); 

Scenario_Tight_LTV = combine_mods({'A_Declaration.mod','B_Calibration_005_tight.mod','C_Model.mod',...
                              'D_SS.mod','E_Shocks.mod','F_Irfs.mod'},...
                              'Scenario_Tight_LTV.mod'); 

Scenario_Eps_2 = combine_mods({'A_Declaration.mod','B_Calibration_005_Eps_2.mod','C_Model.mod',...
                              'D_SS.mod','E_Shocks.mod','F_Irfs.mod'},...
                              'Scenario_Eps_2.mod'); 

Scenario_J_12 = combine_mods({'A_Declaration.mod','B_Calibration_005_J_12.mod','C_Model.mod',...
                              'D_SS.mod','E_Shocks.mod','F_Irfs.mod'},...
                              'Scenario_J_12.mod'); 

Scenario_tau_check = combine_mods({'A_Declaration.mod','B_Calibration_005_tau.mod','C_Model.mod',...
                              'D_SS.mod','E_Shocks.mod','F_Irfs.mod'},...
                              'Scenario_tau_check.mod'); 

Scenario_tau_Tight_LTV = combine_mods({'A_Declaration.mod','B_Calibration_005_tau_tight.mod','C_Model.mod',...
                              'D_SS.mod','E_Shocks.mod','F_Irfs.mod'},...
                              'Scenario_tau_tight.mod'); 